Ruby on Rails capstone project - Budget app
Gmanlove/Budget-app pull request #1
Opened 2023-07-06 11:47 UTC by Gmanlove

### **Highlights 🌟**

- Splash Screen is created.

- The homepage is created and all implementations are complete.

- The transactions page is complete.

- The 'Add Category' and 'Add Transaction' forms are implemented.

- All unit and integration tests are written.

2023-07-06 13:12 UTC, franclobo requested changes
Hi @Gmanlove, 

# ♻️ REQUIRED CHANGES ♻️ 

![so-close-jim-halpert](https://github.com/Gmanlove/Budget-app/assets/58642949/a50220b1-a7ec-4559-af38-bef46d0deb18)

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Highlights

- Use devise, cancancan, psql ✔️ 
- Good UI and UX ✔️ 
- All tests passed ✔️ 
- Professional documentation ✔️ 

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-07-06 13:12 UTC, franclobo commented on app/views/expenses/index.html.erb
> +<%= render partial: 'shared/header',locals: {left:'back', path:root_path ,middle: 'EXPENSES $'+ number_with_precision(@expenses_sum, precision: 2).to_s }%>
- [ ] When I tried to back to the previous page after adding expenses an error occurred, please fix this issue for a better user experience 👇🏽 

![image](https://github.com/Gmanlove/Budget-app/assets/58642949/82222879-7250-43c7-a85a-18a4e05b505e)

2023-07-06 13:44 UTC, Gmanlove commented on app/views/expenses/index.html.erb
> +<%= render partial: 'shared/header',locals: {left:'back', path:root_path ,middle: 'EXPENSES $'+ number_with_precision(@expenses_sum, precision: 2).to_s }%>
Hello @franclobo, please the app is working perfectly well on my own end both online and local machine..... The error might be due network failure from your end. thanks

2023-07-07 00:32 UTC, codecaiine approved these changes
Hi @Gmanlove , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good UI DESIGN ✔️ 
- Good project implementation ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-07 20:07 UTC, merged